# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171117_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('language', models.CharField(choices=[('HI', 'Hindi'), ('EN', 'English')], max_length=10)),
                ('file', models.FileField(unique=True, upload_to='presentation/')),
            ],
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='start_date',
        ),
    ]
