# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171118_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workshop')),
            ],
        ),
    ]
