# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171122_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='branch',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MBA', 'MBA'), ('CS', 'CS'), ('IT', 'IT'), ('ECE', 'ECE'), ('EN', 'EN'), ('ME', 'ME'), ('EI', 'EI'), ('CE', 'CE')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='student_no',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=None, null=True),
        ),
    ]
