# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171125_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='year',
            field=models.IntegerField(choices=[(0, '----'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=None, null=True),
        ),
    ]
