# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190313_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('None', 'None')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
