# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-15 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.CharField(default='', max_length=25),
        ),
    ]
