# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-06 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_charts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='position',
        ),
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
