# Generated by Django 2.2.2 on 2019-08-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190727_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(unique=True, upload_to='home_slider/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Page')),
            ],
        ),
    ]
